// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ct.proto

package pl.cloudtechnologie.itf.proto;

public final class CtProtos {
  private CtProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BidRequestNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.cloudtechnologie.itf.proto.BidRequestNotification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>int64 host_hash = 2;</code>
     */
    long getHostHash();

    /**
     * <code>int32 user_agent = 3;</code>
     */
    int getUserAgent();

    /**
     * <code>int32 ip_address = 4;</code>
     */
    int getIpAddress();

    /**
     * <code>int64 timestamp = 5;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code pl.cloudtechnologie.itf.proto.BidRequestNotification}
   */
  public  static final class BidRequestNotification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.cloudtechnologie.itf.proto.BidRequestNotification)
      BidRequestNotificationOrBuilder {
    // Use BidRequestNotification.newBuilder() to construct.
    private BidRequestNotification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BidRequestNotification() {
      userId_ = 0L;
      hostHash_ = 0L;
      userAgent_ = 0;
      ipAddress_ = 0;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BidRequestNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 16: {

              hostHash_ = input.readInt64();
              break;
            }
            case 24: {

              userAgent_ = input.readInt32();
              break;
            }
            case 32: {

              ipAddress_ = input.readInt32();
              break;
            }
            case 40: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.class, pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int HOST_HASH_FIELD_NUMBER = 2;
    private long hostHash_;
    /**
     * <code>int64 host_hash = 2;</code>
     */
    public long getHostHash() {
      return hostHash_;
    }

    public static final int USER_AGENT_FIELD_NUMBER = 3;
    private int userAgent_;
    /**
     * <code>int32 user_agent = 3;</code>
     */
    public int getUserAgent() {
      return userAgent_;
    }

    public static final int IP_ADDRESS_FIELD_NUMBER = 4;
    private int ipAddress_;
    /**
     * <code>int32 ip_address = 4;</code>
     */
    public int getIpAddress() {
      return ipAddress_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (hostHash_ != 0L) {
        output.writeInt64(2, hostHash_);
      }
      if (userAgent_ != 0) {
        output.writeInt32(3, userAgent_);
      }
      if (ipAddress_ != 0) {
        output.writeInt32(4, ipAddress_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (hostHash_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, hostHash_);
      }
      if (userAgent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userAgent_);
      }
      if (ipAddress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ipAddress_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification)) {
        return super.equals(obj);
      }
      pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification other = (pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getHostHash()
          == other.getHostHash());
      result = result && (getUserAgent()
          == other.getUserAgent());
      result = result && (getIpAddress()
          == other.getIpAddress());
      result = result && (getTimestamp()
          == other.getTimestamp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + HOST_HASH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHostHash());
      hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAgent();
      hash = (37 * hash) + IP_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getIpAddress();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.cloudtechnologie.itf.proto.BidRequestNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.cloudtechnologie.itf.proto.BidRequestNotification)
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.class, pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.Builder.class);
      }

      // Construct using pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        hostHash_ = 0L;

        userAgent_ = 0;

        ipAddress_ = 0;

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification getDefaultInstanceForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.getDefaultInstance();
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification build() {
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification buildPartial() {
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification result = new pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification(this);
        result.userId_ = userId_;
        result.hostHash_ = hostHash_;
        result.userAgent_ = userAgent_;
        result.ipAddress_ = ipAddress_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification) {
          return mergeFrom((pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification other) {
        if (other == pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getHostHash() != 0L) {
          setHostHash(other.getHostHash());
        }
        if (other.getUserAgent() != 0) {
          setUserAgent(other.getUserAgent());
        }
        if (other.getIpAddress() != 0) {
          setIpAddress(other.getIpAddress());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long hostHash_ ;
      /**
       * <code>int64 host_hash = 2;</code>
       */
      public long getHostHash() {
        return hostHash_;
      }
      /**
       * <code>int64 host_hash = 2;</code>
       */
      public Builder setHostHash(long value) {
        
        hostHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 host_hash = 2;</code>
       */
      public Builder clearHostHash() {
        
        hostHash_ = 0L;
        onChanged();
        return this;
      }

      private int userAgent_ ;
      /**
       * <code>int32 user_agent = 3;</code>
       */
      public int getUserAgent() {
        return userAgent_;
      }
      /**
       * <code>int32 user_agent = 3;</code>
       */
      public Builder setUserAgent(int value) {
        
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_agent = 3;</code>
       */
      public Builder clearUserAgent() {
        
        userAgent_ = 0;
        onChanged();
        return this;
      }

      private int ipAddress_ ;
      /**
       * <code>int32 ip_address = 4;</code>
       */
      public int getIpAddress() {
        return ipAddress_;
      }
      /**
       * <code>int32 ip_address = 4;</code>
       */
      public Builder setIpAddress(int value) {
        
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ip_address = 4;</code>
       */
      public Builder clearIpAddress() {
        
        ipAddress_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pl.cloudtechnologie.itf.proto.BidRequestNotification)
    }

    // @@protoc_insertion_point(class_scope:pl.cloudtechnologie.itf.proto.BidRequestNotification)
    private static final pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification();
    }

    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BidRequestNotification>
        PARSER = new com.google.protobuf.AbstractParser<BidRequestNotification>() {
      public BidRequestNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BidRequestNotification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BidRequestNotification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BidRequestNotification> getParserForType() {
      return PARSER;
    }

    public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalculateSegmentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pl.cloudtechnologie.itf.proto.CalculateSegments)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>int64 msg_count = 2;</code>
     */
    long getMsgCount();
  }
  /**
   * Protobuf type {@code pl.cloudtechnologie.itf.proto.CalculateSegments}
   */
  public  static final class CalculateSegments extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pl.cloudtechnologie.itf.proto.CalculateSegments)
      CalculateSegmentsOrBuilder {
    // Use CalculateSegments.newBuilder() to construct.
    private CalculateSegments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalculateSegments() {
      userId_ = 0L;
      msgCount_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CalculateSegments(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 16: {

              msgCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.class, pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int MSG_COUNT_FIELD_NUMBER = 2;
    private long msgCount_;
    /**
     * <code>int64 msg_count = 2;</code>
     */
    public long getMsgCount() {
      return msgCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (msgCount_ != 0L) {
        output.writeInt64(2, msgCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (msgCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, msgCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments)) {
        return super.equals(obj);
      }
      pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments other = (pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getMsgCount()
          == other.getMsgCount());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + MSG_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgCount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.cloudtechnologie.itf.proto.CalculateSegments}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pl.cloudtechnologie.itf.proto.CalculateSegments)
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegmentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.class, pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.Builder.class);
      }

      // Construct using pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        msgCount_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments getDefaultInstanceForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.getDefaultInstance();
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments build() {
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments buildPartial() {
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments result = new pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments(this);
        result.userId_ = userId_;
        result.msgCount_ = msgCount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments) {
          return mergeFrom((pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments other) {
        if (other == pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getMsgCount() != 0L) {
          setMsgCount(other.getMsgCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long msgCount_ ;
      /**
       * <code>int64 msg_count = 2;</code>
       */
      public long getMsgCount() {
        return msgCount_;
      }
      /**
       * <code>int64 msg_count = 2;</code>
       */
      public Builder setMsgCount(long value) {
        
        msgCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msg_count = 2;</code>
       */
      public Builder clearMsgCount() {
        
        msgCount_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pl.cloudtechnologie.itf.proto.CalculateSegments)
    }

    // @@protoc_insertion_point(class_scope:pl.cloudtechnologie.itf.proto.CalculateSegments)
    private static final pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments();
    }

    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculateSegments>
        PARSER = new com.google.protobuf.AbstractParser<CalculateSegments>() {
      public CalculateSegments parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CalculateSegments(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalculateSegments> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculateSegments> getParserForType() {
      return PARSER;
    }

    public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010Ct.proto\022\035pl.cloudtechnologie.itf.prot" +
      "o\"w\n\026BidRequestNotification\022\017\n\007user_id\030\001" +
      " \001(\003\022\021\n\thost_hash\030\002 \001(\003\022\022\n\nuser_agent\030\003 " +
      "\001(\005\022\022\n\nip_address\030\004 \001(\005\022\021\n\ttimestamp\030\005 \001" +
      "(\003\"7\n\021CalculateSegments\022\017\n\007user_id\030\001 \001(\003" +
      "\022\021\n\tmsg_count\030\002 \001(\003B)\n\035pl.cloudtechnolog" +
      "ie.itf.protoB\010CtProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor,
        new java.lang.String[] { "UserId", "HostHash", "UserAgent", "IpAddress", "Timestamp", });
    internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor,
        new java.lang.String[] { "UserId", "MsgCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
