// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: itf/src/main/proto/Ct.proto

package pl.cloudtechnologie.itf.proto;

public final class CtProtos {
  private CtProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BidRequestNotificationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 user_id = 1;
    /**
     * <code>required int64 user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 user_id = 1;</code>
     */
    long getUserId();

    // required int64 host_hash = 2;
    /**
     * <code>required int64 host_hash = 2;</code>
     */
    boolean hasHostHash();
    /**
     * <code>required int64 host_hash = 2;</code>
     */
    long getHostHash();

    // required int32 user_agent = 3;
    /**
     * <code>required int32 user_agent = 3;</code>
     */
    boolean hasUserAgent();
    /**
     * <code>required int32 user_agent = 3;</code>
     */
    int getUserAgent();

    // required int32 ip_address = 4;
    /**
     * <code>required int32 ip_address = 4;</code>
     */
    boolean hasIpAddress();
    /**
     * <code>required int32 ip_address = 4;</code>
     */
    int getIpAddress();

    // required int64 timestamp = 5;
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code pl.cloudtechnologie.itf.proto.BidRequestNotification}
   */
  public static final class BidRequestNotification extends
      com.google.protobuf.GeneratedMessage
      implements BidRequestNotificationOrBuilder {
    // Use BidRequestNotification.newBuilder() to construct.
    private BidRequestNotification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BidRequestNotification(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BidRequestNotification defaultInstance;
    public static BidRequestNotification getDefaultInstance() {
      return defaultInstance;
    }

    public BidRequestNotification getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BidRequestNotification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hostHash_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userAgent_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ipAddress_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.class, pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.Builder.class);
    }

    public static com.google.protobuf.Parser<BidRequestNotification> PARSER =
        new com.google.protobuf.AbstractParser<BidRequestNotification>() {
      public BidRequestNotification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BidRequestNotification(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BidRequestNotification> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // required int64 host_hash = 2;
    public static final int HOST_HASH_FIELD_NUMBER = 2;
    private long hostHash_;
    /**
     * <code>required int64 host_hash = 2;</code>
     */
    public boolean hasHostHash() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 host_hash = 2;</code>
     */
    public long getHostHash() {
      return hostHash_;
    }

    // required int32 user_agent = 3;
    public static final int USER_AGENT_FIELD_NUMBER = 3;
    private int userAgent_;
    /**
     * <code>required int32 user_agent = 3;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 user_agent = 3;</code>
     */
    public int getUserAgent() {
      return userAgent_;
    }

    // required int32 ip_address = 4;
    public static final int IP_ADDRESS_FIELD_NUMBER = 4;
    private int ipAddress_;
    /**
     * <code>required int32 ip_address = 4;</code>
     */
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 ip_address = 4;</code>
     */
    public int getIpAddress() {
      return ipAddress_;
    }

    // required int64 timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      userId_ = 0L;
      hostHash_ = 0L;
      userAgent_ = 0;
      ipAddress_ = 0;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHostHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserAgent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, hostHash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userAgent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ipAddress_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, hostHash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userAgent_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ipAddress_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.cloudtechnologie.itf.proto.BidRequestNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.class, pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.Builder.class);
      }

      // Construct using pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        hostHash_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userAgent_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ipAddress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification getDefaultInstanceForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.getDefaultInstance();
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification build() {
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification buildPartial() {
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification result = new pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hostHash_ = hostHash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ipAddress_ = ipAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification) {
          return mergeFrom((pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification other) {
        if (other == pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasHostHash()) {
          setHostHash(other.getHostHash());
        }
        if (other.hasUserAgent()) {
          setUserAgent(other.getUserAgent());
        }
        if (other.hasIpAddress()) {
          setIpAddress(other.getIpAddress());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasHostHash()) {
          
          return false;
        }
        if (!hasUserAgent()) {
          
          return false;
        }
        if (!hasIpAddress()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.cloudtechnologie.itf.proto.CtProtos.BidRequestNotification) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 user_id = 1;
      private long userId_ ;
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 host_hash = 2;
      private long hostHash_ ;
      /**
       * <code>required int64 host_hash = 2;</code>
       */
      public boolean hasHostHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 host_hash = 2;</code>
       */
      public long getHostHash() {
        return hostHash_;
      }
      /**
       * <code>required int64 host_hash = 2;</code>
       */
      public Builder setHostHash(long value) {
        bitField0_ |= 0x00000002;
        hostHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 host_hash = 2;</code>
       */
      public Builder clearHostHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hostHash_ = 0L;
        onChanged();
        return this;
      }

      // required int32 user_agent = 3;
      private int userAgent_ ;
      /**
       * <code>required int32 user_agent = 3;</code>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 user_agent = 3;</code>
       */
      public int getUserAgent() {
        return userAgent_;
      }
      /**
       * <code>required int32 user_agent = 3;</code>
       */
      public Builder setUserAgent(int value) {
        bitField0_ |= 0x00000004;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 user_agent = 3;</code>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userAgent_ = 0;
        onChanged();
        return this;
      }

      // required int32 ip_address = 4;
      private int ipAddress_ ;
      /**
       * <code>required int32 ip_address = 4;</code>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 ip_address = 4;</code>
       */
      public int getIpAddress() {
        return ipAddress_;
      }
      /**
       * <code>required int32 ip_address = 4;</code>
       */
      public Builder setIpAddress(int value) {
        bitField0_ |= 0x00000008;
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ip_address = 4;</code>
       */
      public Builder clearIpAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ipAddress_ = 0;
        onChanged();
        return this;
      }

      // required int64 timestamp = 5;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pl.cloudtechnologie.itf.proto.BidRequestNotification)
    }

    static {
      defaultInstance = new BidRequestNotification(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pl.cloudtechnologie.itf.proto.BidRequestNotification)
  }

  public interface CalculateSegmentsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 user_id = 1;
    /**
     * <code>required int64 user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 user_id = 1;</code>
     */
    long getUserId();

    // required int64 msg_count = 2;
    /**
     * <code>required int64 msg_count = 2;</code>
     */
    boolean hasMsgCount();
    /**
     * <code>required int64 msg_count = 2;</code>
     */
    long getMsgCount();
  }
  /**
   * Protobuf type {@code pl.cloudtechnologie.itf.proto.CalculateSegments}
   */
  public static final class CalculateSegments extends
      com.google.protobuf.GeneratedMessage
      implements CalculateSegmentsOrBuilder {
    // Use CalculateSegments.newBuilder() to construct.
    private CalculateSegments(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CalculateSegments(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CalculateSegments defaultInstance;
    public static CalculateSegments getDefaultInstance() {
      return defaultInstance;
    }

    public CalculateSegments getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CalculateSegments(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.class, pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.Builder.class);
    }

    public static com.google.protobuf.Parser<CalculateSegments> PARSER =
        new com.google.protobuf.AbstractParser<CalculateSegments>() {
      public CalculateSegments parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculateSegments(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CalculateSegments> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // required int64 msg_count = 2;
    public static final int MSG_COUNT_FIELD_NUMBER = 2;
    private long msgCount_;
    /**
     * <code>required int64 msg_count = 2;</code>
     */
    public boolean hasMsgCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 msg_count = 2;</code>
     */
    public long getMsgCount() {
      return msgCount_;
    }

    private void initFields() {
      userId_ = 0L;
      msgCount_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, msgCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, msgCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pl.cloudtechnologie.itf.proto.CalculateSegments}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegmentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.class, pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.Builder.class);
      }

      // Construct using pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments getDefaultInstanceForType() {
        return pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.getDefaultInstance();
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments build() {
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments buildPartial() {
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments result = new pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgCount_ = msgCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments) {
          return mergeFrom((pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments other) {
        if (other == pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMsgCount()) {
          setMsgCount(other.getMsgCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasMsgCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pl.cloudtechnologie.itf.proto.CtProtos.CalculateSegments) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 user_id = 1;
      private long userId_ ;
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 msg_count = 2;
      private long msgCount_ ;
      /**
       * <code>required int64 msg_count = 2;</code>
       */
      public boolean hasMsgCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 msg_count = 2;</code>
       */
      public long getMsgCount() {
        return msgCount_;
      }
      /**
       * <code>required int64 msg_count = 2;</code>
       */
      public Builder setMsgCount(long value) {
        bitField0_ |= 0x00000002;
        msgCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 msg_count = 2;</code>
       */
      public Builder clearMsgCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgCount_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pl.cloudtechnologie.itf.proto.CalculateSegments)
    }

    static {
      defaultInstance = new CalculateSegments(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pl.cloudtechnologie.itf.proto.CalculateSegments)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033itf/src/main/proto/Ct.proto\022\035pl.cloudt" +
      "echnologie.itf.proto\"w\n\026BidRequestNotifi" +
      "cation\022\017\n\007user_id\030\001 \002(\003\022\021\n\thost_hash\030\002 \002" +
      "(\003\022\022\n\nuser_agent\030\003 \002(\005\022\022\n\nip_address\030\004 \002" +
      "(\005\022\021\n\ttimestamp\030\005 \002(\003\"7\n\021CalculateSegmen" +
      "ts\022\017\n\007user_id\030\001 \002(\003\022\021\n\tmsg_count\030\002 \002(\003B)" +
      "\n\035pl.cloudtechnologie.itf.protoB\010CtProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_cloudtechnologie_itf_proto_BidRequestNotification_descriptor,
              new java.lang.String[] { "UserId", "HostHash", "UserAgent", "IpAddress", "Timestamp", });
          internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pl_cloudtechnologie_itf_proto_CalculateSegments_descriptor,
              new java.lang.String[] { "UserId", "MsgCount", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
