/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.cloudtechnologie.itf.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroBidRequestNotification extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2718152149905906908L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroBidRequestNotification\",\"namespace\":\"pl.cloudtechnologie.itf.avro\",\"fields\":[{\"name\":\"user_id\",\"type\":[\"long\"]},{\"name\":\"host_hash\",\"type\":[\"long\"]},{\"name\":\"user_agent\",\"type\":[\"int\"]},{\"name\":\"ip_address\",\"type\":[\"int\"]},{\"name\":\"timestamp\",\"type\":[\"long\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.Object user_id;
   private java.lang.Object host_hash;
   private java.lang.Object user_agent;
   private java.lang.Object ip_address;
   private java.lang.Object timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroBidRequestNotification() {}

  /**
   * All-args constructor.
   * @param user_id The new value for user_id
   * @param host_hash The new value for host_hash
   * @param user_agent The new value for user_agent
   * @param ip_address The new value for ip_address
   * @param timestamp The new value for timestamp
   */
  public AvroBidRequestNotification(java.lang.Object user_id, java.lang.Object host_hash, java.lang.Object user_agent, java.lang.Object ip_address, java.lang.Object timestamp) {
    this.user_id = user_id;
    this.host_hash = host_hash;
    this.user_agent = user_agent;
    this.ip_address = ip_address;
    this.timestamp = timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return host_hash;
    case 2: return user_agent;
    case 3: return ip_address;
    case 4: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = (java.lang.Object)value$; break;
    case 1: host_hash = (java.lang.Object)value$; break;
    case 2: user_agent = (java.lang.Object)value$; break;
    case 3: ip_address = (java.lang.Object)value$; break;
    case 4: timestamp = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.Object getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.Object value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'host_hash' field.
   * @return The value of the 'host_hash' field.
   */
  public java.lang.Object getHostHash() {
    return host_hash;
  }

  /**
   * Sets the value of the 'host_hash' field.
   * @param value the value to set.
   */
  public void setHostHash(java.lang.Object value) {
    this.host_hash = value;
  }

  /**
   * Gets the value of the 'user_agent' field.
   * @return The value of the 'user_agent' field.
   */
  public java.lang.Object getUserAgent() {
    return user_agent;
  }

  /**
   * Sets the value of the 'user_agent' field.
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.Object value) {
    this.user_agent = value;
  }

  /**
   * Gets the value of the 'ip_address' field.
   * @return The value of the 'ip_address' field.
   */
  public java.lang.Object getIpAddress() {
    return ip_address;
  }

  /**
   * Sets the value of the 'ip_address' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.Object value) {
    this.ip_address = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Object getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Object value) {
    this.timestamp = value;
  }

  /**
   * Creates a new AvroBidRequestNotification RecordBuilder.
   * @return A new AvroBidRequestNotification RecordBuilder
   */
  public static pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder newBuilder() {
    return new pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder();
  }

  /**
   * Creates a new AvroBidRequestNotification RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroBidRequestNotification RecordBuilder
   */
  public static pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder newBuilder(pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder other) {
    return new pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder(other);
  }

  /**
   * Creates a new AvroBidRequestNotification RecordBuilder by copying an existing AvroBidRequestNotification instance.
   * @param other The existing instance to copy.
   * @return A new AvroBidRequestNotification RecordBuilder
   */
  public static pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder newBuilder(pl.cloudtechnologie.itf.avro.AvroBidRequestNotification other) {
    return new pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder(other);
  }

  /**
   * RecordBuilder for AvroBidRequestNotification instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroBidRequestNotification>
    implements org.apache.avro.data.RecordBuilder<AvroBidRequestNotification> {

    private java.lang.Object user_id;
    private java.lang.Object host_hash;
    private java.lang.Object user_agent;
    private java.lang.Object ip_address;
    private java.lang.Object timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host_hash)) {
        this.host_hash = data().deepCopy(fields()[1].schema(), other.host_hash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[2].schema(), other.user_agent);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ip_address)) {
        this.ip_address = data().deepCopy(fields()[3].schema(), other.ip_address);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroBidRequestNotification instance
     * @param other The existing instance to copy.
     */
    private Builder(pl.cloudtechnologie.itf.avro.AvroBidRequestNotification other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host_hash)) {
        this.host_hash = data().deepCopy(fields()[1].schema(), other.host_hash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[2].schema(), other.user_agent);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ip_address)) {
        this.ip_address = data().deepCopy(fields()[3].schema(), other.ip_address);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.Object getUserId() {
      return user_id;
    }

    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder setUserId(java.lang.Object value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'host_hash' field.
      * @return The value.
      */
    public java.lang.Object getHostHash() {
      return host_hash;
    }

    /**
      * Sets the value of the 'host_hash' field.
      * @param value The value of 'host_hash'.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder setHostHash(java.lang.Object value) {
      validate(fields()[1], value);
      this.host_hash = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'host_hash' field has been set.
      * @return True if the 'host_hash' field has been set, false otherwise.
      */
    public boolean hasHostHash() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'host_hash' field.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder clearHostHash() {
      host_hash = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_agent' field.
      * @return The value.
      */
    public java.lang.Object getUserAgent() {
      return user_agent;
    }

    /**
      * Sets the value of the 'user_agent' field.
      * @param value The value of 'user_agent'.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder setUserAgent(java.lang.Object value) {
      validate(fields()[2], value);
      this.user_agent = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'user_agent' field has been set.
      * @return True if the 'user_agent' field has been set, false otherwise.
      */
    public boolean hasUserAgent() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'user_agent' field.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder clearUserAgent() {
      user_agent = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ip_address' field.
      * @return The value.
      */
    public java.lang.Object getIpAddress() {
      return ip_address;
    }

    /**
      * Sets the value of the 'ip_address' field.
      * @param value The value of 'ip_address'.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder setIpAddress(java.lang.Object value) {
      validate(fields()[3], value);
      this.ip_address = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ip_address' field has been set.
      * @return True if the 'ip_address' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ip_address' field.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder clearIpAddress() {
      ip_address = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Object getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder setTimestamp(java.lang.Object value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public pl.cloudtechnologie.itf.avro.AvroBidRequestNotification.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public AvroBidRequestNotification build() {
      try {
        AvroBidRequestNotification record = new AvroBidRequestNotification();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.Object) defaultValue(fields()[0]);
        record.host_hash = fieldSetFlags()[1] ? this.host_hash : (java.lang.Object) defaultValue(fields()[1]);
        record.user_agent = fieldSetFlags()[2] ? this.user_agent : (java.lang.Object) defaultValue(fields()[2]);
        record.ip_address = fieldSetFlags()[3] ? this.ip_address : (java.lang.Object) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Object) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
